# 开发环境Docker Compose配置
version: '3.8'

services:
  # 开发环境后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/file-social-platform-dev?authSource=admin
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: dev-jwt-secret-key
      JWT_REFRESH_SECRET: dev-refresh-secret-key
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    command: npm run dev

  # 开发环境前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_URL: http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    command: npm run dev
    ports:
      - "3000:3000"

  # 开发环境MongoDB（数据持久化到本地）
  mongodb:
    volumes:
      - ./data/mongodb:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  # 开发环境Redis
  redis:
    volumes:
      - ./data/redis:/data